apiVersion: apps/v1
kind: Deployment

metadata:
  name: basic-devops

spec:
  replicas: 3

  selector:
    matchLabels:
      app: basic-devops

  template:
    metadata:
      labels:
        app: basic-devops

    spec:
      containers:
        - name: basic-devops
          image: nginx:alpine
          ports:
            - containerPort: 80